class ClientHttpAccessConstant:
    operation = 'operation'
    stock_code = 'stock_code'
    price = 'price'
    amount = 'amount'
    entrust_type = 'entrust_type'
    entrust_id = 'entrust_id'
    account_info_type = 'account_info_type'
    buy = 'buy'
    sell = 'sell'
    cancel_entrust = 'cancel_entrust'
    query = 'query'
    buy_or_sell = 'buy_or_sell'
    query_account_info = 'query_account_info'
    query_day_entrust = 'query_day_entrust'
    all = 'all'
    myshare = 'myshare'
    dayentrust = 'dayentrust'
    dayfinentrust = 'dayfinentrust'
    hisentrust = 'hisentrust'
    hisfinentrust = 'hisfinentrust'
    moneymovement = 'moneymovement'
    deliveryentrust = 'deliveryentrust'


kca_ = ClientHttpAccessConstant
