class ClientConstant:
    account_info = 'account_info'
    myshare = 'myshare'
    dayentrust = 'dayentrust'
    dayfinentrust = 'dayfinentrust'
    cancelentrust = 'cancelentrust'
    hisentrust = 'hisentrust'
    hisfinentrust = 'hisfinentrust'
    moneymovement = 'moneymovement'
    deliveryentrust = 'deliveryentrust'
